#!/usr/bin/env bash
# Generate the Ansible inventory from Terraform state.
#
# This is the dynamic inventory: addresses are never hardcoded anywhere in the
# Ansible tree, they come from `terraform output -json`. Re-applying with a
# different zone or CIDR changes the inventory automatically, and there is no
# second place to update and forget.
#
# The ProxyJump chain is the interesting part and mirrors the topology exactly:
#
#   bastion, nginx   direct        (public tier, they have public addresses)
#   app              via bastion   (apps tier, no public address)
#   db               via bastion THEN app
#
# The db needs two hops because public and dbs are NOT peered. The bastion has
# no route to the database at all, so it cannot be jumped through directly -
# the chain has to land in the apps tier first. That is the peering
# non-transitivity showing up in the operator's tooling, not just in a diagram.

set -uo pipefail

STACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$STACK_DIR/terraform"
OUT="$STACK_DIR/ansible/inventory/hosts.yml"
KEY="/tmp/k"   # installed 0600 by scripts/ansible-run.sh; a bind mount cannot hold 0600

cd "$TF_DIR"

if ! terraform output -json inventory > /dev/null 2>&1; then
  echo "ERROR: no terraform outputs. Has apply run?" >&2
  exit 1
fi

INV="$(terraform output -json inventory)"

# Pull values without needing jq on the host.
val() { echo "$INV" | python -c "import json,sys;d=json.load(sys.stdin);print(eval('d'+sys.argv[1]))" "$1" 2>/dev/null; }

SSH_USER="$(val "['ssh_user']")"
BASTION_IP="$(val "['bastion_ip']")"
NGINX_IP="$(val "['hosts']['nginx']['ansible_host']")"
NGINX_PRIV="$(val "['hosts']['nginx']['private_ip']")"
APP_IP="$(val "['hosts']['app']['ansible_host']")"
DB_IP="$(val "['hosts']['db']['ansible_host']")"

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<YAML
# GENERATED by scripts/inventory.sh from terraform output. Do not edit.
# Regenerate after every apply.
#
# ProxyJump is used rather than a hand-rolled ProxyCommand. A two-hop chain
# written as a nested ProxyCommand needs quotes inside quotes inside YAML, and
# the db entry failed exactly that way - "timed out during banner exchange",
# which looks like a firewall problem and is really a mangled command line.
# ProxyJump takes a comma-separated chain natively and needs no nesting.
# The identity is supplied by /tmp/ssh_config, which ansible-run.sh writes,
# because -i applies only to the final hop and not to the jumps.
all:
  vars:
    ansible_user: ${SSH_USER}
    ansible_python_interpreter: /usr/bin/python3
    bastion_ip: ${BASTION_IP}
    app_private_ip: ${APP_IP}
    db_private_ip: ${DB_IP}
    nginx_private_ip: ${NGINX_PRIV}

  children:
    public_tier:
      hosts:
        bastion:
          ansible_host: ${BASTION_IP}
        nginx:
          # Public address serves 443 to the internet; SSH from outside is
          # refused by the firewall, so admin access goes through the bastion.
          ansible_host: ${NGINX_PRIV}
          ansible_ssh_common_args: -o ProxyJump=${SSH_USER}@${BASTION_IP}

    apps_tier:
      hosts:
        app:
          ansible_host: ${APP_IP}
          # One hop: the bastion peers with the apps VPC.
          ansible_ssh_common_args: -o ProxyJump=${SSH_USER}@${BASTION_IP}

    dbs_tier:
      hosts:
        db:
          ansible_host: ${DB_IP}
          # TWO hops. public and dbs are NOT peered, so the bastion has no
          # route to the database and cannot be jumped through directly - the
          # chain must land in the apps tier first. Peering non-transitivity,
          # visible in the operator tooling rather than only in a diagram.
          ansible_ssh_common_args: -o ProxyJump=${SSH_USER}@${BASTION_IP},${SSH_USER}@${APP_IP}
YAML

echo "wrote $OUT"
echo "  bastion : $BASTION_IP (direct)"
echo "  nginx   : $NGINX_PRIV (via bastion; public $NGINX_IP serves 443 only)"
echo "  app     : $APP_IP (via bastion)"
echo "  db      : $DB_IP (via bastion -> app)"
