variable "project_id" {
  description = "GCP project ID."
  type        = string
}

variable "region" {
  description = "Region for all regional resources. Single region keeps cost and latency down."
  type        = string
  default     = "us-central1"
}

variable "zone" {
  description = "Single zone. Multi-zone would be right for production and wrong for a costed exercise."
  type        = string
  default     = "us-central1-a"
}

# ---------------------------------------------------------------------------
# CIDR PLAN
#
# Three separate /16 VPCs, each carrying one /24 subnet today. The /16 gives
# 255 further /24s per tier without ever renumbering, which matters because
# renumbering a peered VPC means tearing down the peering.
#
#   tier     VPC CIDR        subnet in use     hosts   spare /24s
#   public   10.10.0.0/16    10.10.1.0/24      251     255
#   apps     10.20.0.0/16    10.20.1.0/24      251     255
#   dbs      10.30.0.0/16    10.30.1.0/24      251     255
#   vpn      10.99.0.0/24    (WireGuard peers) 251     -
#
# GCP reserves 4 addresses per subnet (network, default gateway, second-to-last,
# broadcast), so a /24 yields 251 usable, not 254.
#
# The ranges are deliberately far apart and non-contiguous. VPC peering REJECTS
# overlapping ranges outright - the peering simply will not become ACTIVE, and
# the error names the overlap rather than failing quietly. Picking 10.10/10.20/
# 10.30 rather than three adjacent /16s also leaves room to summarise a tier
# into a single route later without colliding with a neighbour.
#
# 10.99.0.0/24 for the WireGuard tunnel is outside every VPC range on purpose:
# tunnel addresses must not collide with anything routable, or the VPN client
# cannot tell whether to send a packet down the tunnel or out its own NIC.
# ---------------------------------------------------------------------------

variable "public_cidr" {
  description = "Public tier VPC range (nginx reverse proxy, bastion/VPN)."
  type        = string
  default     = "10.10.0.0/16"
}

variable "public_subnet_cidr" {
  description = "Public tier subnet."
  type        = string
  default     = "10.10.1.0/24"
}

variable "apps_cidr" {
  description = "Application tier VPC range."
  type        = string
  default     = "10.20.0.0/16"
}

variable "apps_subnet_cidr" {
  description = "Application tier subnet."
  type        = string
  default     = "10.20.1.0/24"
}

variable "dbs_cidr" {
  description = "Database tier VPC range."
  type        = string
  default     = "10.30.0.0/16"
}

variable "dbs_subnet_cidr" {
  description = "Database tier subnet."
  type        = string
  default     = "10.30.1.0/24"
}

variable "vpn_cidr" {
  description = "WireGuard tunnel range. Must not overlap any VPC range."
  type        = string
  default     = "10.99.0.0/24"
}

# ---------------------------------------------------------------------------
# Sizing. e2-micro throughout: 2 shared vCPU, 1 GB. Shared-core means bursty
# work is slow rather than broken, which is an acceptable trade for an
# exercise that is billed by the hour.
# ---------------------------------------------------------------------------

variable "machine_type" {
  description = "Machine type for all instances. e2-micro is the cheapest that runs the stack."
  type        = string
  default     = "e2-micro"
}

variable "boot_disk_size_gb" {
  description = "Boot disk size. 10 GB is the minimum for the Debian image."
  type        = number
  default     = 10
}

variable "boot_disk_type" {
  description = "pd-standard is cheaper than pd-balanced and fast enough here."
  type        = string
  default     = "pd-standard"
}

variable "boot_image" {
  description = "Debian 12. Matches the Ansible roles and the Task 02/03 containers."
  type        = string
  default     = "debian-cloud/debian-12"
}

variable "ssh_user" {
  description = "Login name for the SSH key placed in instance metadata."
  type        = string
  default     = "ansible"
}

variable "ssh_public_key" {
  description = "SSH public key for Ansible. Generated by scripts/keygen.sh if absent."
  type        = string
}

variable "admin_source_cidr" {
  description = <<-EOT
    Source range permitted to reach the bastion on SSH and WireGuard.

    Defaults to 0.0.0.0/0 because the operator's public address is dynamic and
    the exercise is short-lived. That is a real weakening and is called out in
    the report rather than hidden: with a fixed office range this should be
    that range, and nothing else. The bastion is the only host that accepts
    anything from the internet besides nginx on 443.
  EOT
  type        = string
  default     = "0.0.0.0/0"
}

variable "labels" {
  description = "Applied to every resource so cost can be attributed and orphans found."
  type        = map(string)
  default = {
    project = "devops-tasks"
    task    = "05-terraform-ansible"
    managed = "terraform"
  }
}
